name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
 
  e2e-tests:
    name: "E2E tests using ${{ matrix.browser }}"
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Debug steps to identify workspace issues
      - name: Debug workspace
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Package.json contents:"
          cat package.json
          echo "pnpm workspace config:"
          cat pnpm-workspace.yaml || echo "No workspace config found"
          echo "Available packages:"
          pnpm ls -r
          pwd

      - name: Install project dependencies
        run: pnpm i

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm --filter "server-function-test" dev
          browser: ${{ matrix.browser }}
